---
title: "Análisis descriptivo"
---

```{r include=FALSE}
source("00_datos/source.R")
```

## 1. Estadísticos básicos

Lista con los estadísticos descriptivos básicos: `summary()`

```{r}
summary(datos$edad)
```

También se puede obtener un único estadístico de interés: `min()`, `max()`, `median()`, `mean()`, `sd()`

------------------------------------------------------------------------

## 2. Tablas de frecuencias

Con el comando `table`:

``` r
table(datos$variable)
```

-   Ej.:

```{r}
table(datos$estudios)
```

Si queremos ver también los valores perdidos de la variable, se añade al comando original la opción `useNA = "ifany"` (para que muestre los NA solo cuando existan) o `useNA = "always"` (si queremos que aparezca el número de NA incluso si este es 0):

```{r}
table(datos$estudios, useNA = "ifany")
```

Con el comando `count`:

``` r
datos %>% count(variable)
```

-   Ej.:

```{r}
datos %>% count(estudios)
```

*La explicación de cómo hacer tablas de frecuencias bivariadas, así como su interpretación, está en el apartado de análisis bivariado*

------------------------------------------------------------------------
