project:
  type: website
  output-dir: docs

website:
  title: "Apuntes R"
  favicon: 01_img/icono.png
  bread-crumbs: false # Para que elimie de la parte superior las indicaciones de dónde se está (P.ej., que no aparezca: Análisis de datos > Análisis bivariado > Ttest )
  reader-mode: true # La pestañita que aparece arriba para ocultar todos las tablas de contenido
  page-navigation: true # Para que al final de cada página aparezca una opción de ir a la siguiente página o a la anterior.
  back-to-top-navigation: true # Para que al final de cada página aparezca una opción para subir otra vez al principio.
  search: true # Para añadir la lupa a la página

# El menú de navegación superior se escribe del siguiente modo  
  navbar:
    left:
      - text: "Introducción a R"
        href: index.qmd         # El archivo de referencia que se abrirá cuando se pulse sobre esa pestaña
      - text: "Otras cosas"
        href: 99_otras_cosas.qmd
      - text: "Gráficos"
        href: 02_graficos/8g_graficos.qmd
      - text: "Análisis"
        href: 31_analisis_descriptivo.qmd

# El menú lateral se escribe así:
  sidebar:
    - title: "Introducción a R" # Al escribir la opción title, todas las instrucciones y documentos siguientes se aplicarán dentro de la pestaña superior que tiene el mismo nombre.
                                # Es la forma de añadir una subsecció lateral dentro de las pestañas superiores, pero solo para una parte de los archivos, en lugar de mostrarlos todos.
      contents: 
        - index.qmd
        - 02_intro/11_introduccion.qmd
        - 02_intro/12_documentos_r.qmd
        - 02_intro/13_flujos_trabajo.qmd
        - 02_intro/14_operaciones_basicas.qmd
      
    - title: "Otras cosas"
      contents:
        - 9_otras_cosas.qmd
    
    - title: "Análisis descriptivo"
      contents:
        - 31_analisis_descriptivo.qmd
        
    - title: "Gráficos"
      contents:
        - "02_graficos/8g_graficos.qmd"
        - "02_graficos/8g_mancuernas.qmd"
        - "02_graficos/8g_lineas.qmd"
        - "02_graficos/8g_barras.qmd"
        - "02_graficos/8g_otros.qmd"

format:
  html:
    theme: # Se puede añadir una opción para poner la página en modo claro o modo oscuro
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-title: "Contenido"    
    language: es              
    include-in-header:
      - text: |
          <style>
          /* Estilos para todo el documento */
          body {
            text-align: justify;
          }
          /* Estilos específicos para la tabla de contenidos */
          .toc-actions, .toc .nav, .toc .nav > li > a {
            text-align: left !important;
          }
          </style>
      - text: |
          <script>
          // Añadir funcionalidad de zoom para imágenes
          document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('img.zoomable').forEach(function(img) {
              img.addEventListener('click', function() {
                this.classList.toggle('zoomed');
              });
            });
          });
          </script>
 
# Configuración global de knitr
knitr:
  opts_chunk: 
    echo: true
    message: false
    warning: false
    fig.align: center
    out.width: "60%"

editor: visual



# Para publicar la página se escribe lo siguiente en el terminal: quarto publish quarto-pub