{
  "hash": "bcd82848715751c4df995ef13744615a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lineal múltiple\"\n---\n\n```{=html}\n<style>\nbody {\ntext-align: justify}\n</style>\n```\n\n\n\n\n\n\n\nLlamamos regresión lineal múltiple al análisis de regresión que incluye más de una variable independiente. Se representa como:\n\n$$E(y) = \\beta_{0}  + \\beta_{1}{x_{1}} + \\ \\beta_{12}{x_{2}} +  \\beta_{3}{x_{3}} + u$$\n\ndonde **β~0~** es el valor de *y* cuando todas las *x~i~* valen 0, **β~i~** son los coeficientes de las variables independientes y el término **u** es el término de error.\n\nEsta ecuación definiría un hiperplano, pues con una VI se define una recta, con dos VIs un plano, con tres VIs un espacio de tres dimensiones, y así sucesivamente.\n\n### Resumen de las funciones principales\n\n``` r\n# Eliminar los NA de la base de datos\nlista_variables <- c(\"var1\",\"var2\",\"var3\"...)\ndatos_reg <- datos[lista_variables]\ndatos_reg <- na.omit(datos_Reg)\n\n# Función de la regresión\nregresión <- lm(var1~var2 + var3 + var4, datos_reg) #Librería e1071\nsummary(regresión)\n\n#Visualizar los coeficientes\ncoefplot(regresión, xlim=c(-5, 5), col.pts=\"blue\", intercept=TRUE, main=\"Coeficientes de la regresión\") #Librería arm\n\n# Comprobación de los supuestos principales\nplot(regresión,2) #Normalidad de los residuos\nbptest(regresión) #Homocedasticidad (librería lmtest)\nvif(regresión) #Multicolinealidad (librería rms)\n\n# Valores predichos\n\n\n#Exportar los resultados\nstargazer(regresión, type=\"text\") #Librería stargazer\n\n#Comparación de modelos\nAIC(modelo1, modelo2, modelo3)\nBIC(modelo1, modelo2, modelo3)\n```\n\n### Ejemplo práctico\n\nVamos a estimar la propensión de voto a un partido (variable escala) en función de las siguientes variables:\n\n-   edad del entrevistado (variable continua)\n-   sexo (variable dicotómica)\n-   nivel educativo (variable dicotómica)\n-   opinión sobre la situación económica personal (variable dicotómica)\n-   opinión sobre la situación económica en España (variable dicotómica)\n-   recuerdo de voto (variable politómica)\n-   ideología del entrevistado (variable escala)\n\nEs posible que estas variables no configuren un buen modelo. Sin embargo, son un buen ejercicio porque nos permitirá ver cómo se interpretan los diferentes tipos de variables e identificar algunos problemas.\n\n### Preparar la base de datos {#eliminarNA}\n\nLa regresión lineal es \"sensible\" a la existencia de casos perdidos en las variables que se introducen en los modelos. Para evitar que diferentes modelos tengan diferentes número de casos **(en cuyo caso no serían comparables)** creamos un nuevo data.frame que contenga únicamente las columnas que vamos a usar para estimar los modelos, para eliminar de estos los casos perdidos. A continuación, eliminamos todas las filas que continenen valores perdidos. Esto se hace usando la funciones `na.omit()` o `na.exclude()`.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmyvars <- c(\"prop_psoe\", \"prop_pp\", \"edad\", \"hombre\", \"recuerdo19\", \"estudios_universitarios\", \"ideol\", \"ecoper\", \"ecoesp\")   # nuevo data.frame\ndatos_red<-datos[myvars] #Los corchetes sirven para seleccionar solo el conjunto de datos especificado. También podría usarse la función select.\ndatos_red<- na.omit(datos_red)\n```\n:::\n\n\n\n### El modelo de regresión {#modeloreg}\n\nA continuación, esitmamos el modelo de regresión (modelPP) con las variables arriba especificadas. Usaremos la función `lm()` de la libería *e1071* (como ocurre siempre, existen muchas otras librerías que incluyen funciones para estimar regresiones lineales y son igualmente válidas).\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(e1071)\n\nmodelPP <- lm(prop_pp ~ edad + hombre + estudios_universitarios + ecoper + ecoesp + recuerdo19 + ideol, data=datos_red)  \nsummary(modelPP)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = prop_pp ~ edad + hombre + estudios_universitarios + \n    ecoper + ecoesp + recuerdo19 + ideol, data = datos_red)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.6522 -1.4692 -0.2591  1.5518  9.8268 \n\nCoefficients:\n                               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                    0.764501   0.082283   9.291  < 2e-16 ***\nedad                          -0.000385   0.001114  -0.346 0.729637    \nhombreHombre                  -0.045523   0.033180  -1.372 0.170080    \nestudios_universitarioscon EU  0.120337   0.034416   3.497 0.000472 ***\necoperpositiva                 0.173926   0.038775   4.485 7.31e-06 ***\necoesppositiva                -0.729276   0.038624 -18.881  < 2e-16 ***\nrecuerdo19PP                   4.149196   0.055763  74.407  < 2e-16 ***\nrecuerdo19VOX                  0.580711   0.075540   7.687 1.56e-14 ***\nrecuerdo19Podemos             -0.969983   0.056628 -17.129  < 2e-16 ***\nrecuerdo19Ciudadanos           2.837302   0.068713  41.292  < 2e-16 ***\nrecuerdo19Más Madrid          -0.554132   0.189993  -2.917 0.003542 ** \nrecuerdo19Otros               -1.012513   0.052845 -19.160  < 2e-16 ***\nrecuerdo19En blanco            0.666554   0.139864   4.766 1.89e-06 ***\nideol                          0.445504   0.008478  52.549  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.473 on 22880 degrees of freedom\nMultiple R-squared:  0.5873,\tAdjusted R-squared:  0.5871 \nF-statistic:  2505 on 13 and 22880 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nComo podemos observar, R transforma la variable politómica \"recuerdo19\" en c-1 variables. Lo hace porque está definida como factor, de lo contrario trataría la variable como numérica (lo cual no tendría ningún sentido). En este caso, cada variable se interpreta **en relación a la categoría de refencia** (en este caso, PSOE). La función `relevel()` nos permite cambiar cambiar la categoría de referencia. Por ejemplo, si queremos que \"PP\" sea nuestra categoría de referencia, haríamos lo siguiente:\n\nLo único que cambia es la categoría de referencia en la variable recuerdo19 y, por consiguiente, los coeficientes de las dummies. El resto de la tabla será idéntica.\n\n``` r\nmodelPP_newrc<- lm(prop_pp ~ edad + hombre + estudios_universitarios + ecoper + ecoesp +relevel(recuerdo19, ref =\"PP\") + ideol, data=datos_red) \nsummary(modelPP_newrc)\n```\n\n#### Significatividad del modelo\n\nLos resultados muestran que todas las variables menos edad y género son estadísticamente significativas para un NC del 99.9%. Esto es así porque, dado que los p-valores son \\<0.001, podemos rechazar la hipótesis nula con una probabilidad de equivocarnos inferior a 0.001. <br>\n\n### Interpretación de los coeficientes {#coef}\n\nMás allá de la significación estadística, es importante interpretar el tamaño del coeficiente. En otras palabras, la magnitud del efecto. En regresión lineal múltiple, los coeficientes de regresión representan el **cambio promedio que se produce en la VD por cada unidad de cambio en la VI, mientras el resto de variables se mantiene constante** (*ceteris paribus*). Este control estadístico que proporciona la regresión es muy importante, porque aisla el efecto de una variable del resto de variable incluidas en el modelo.\n\nEl valor de los coeficientes se obtiene con la función `sumary()` del modelo, y también puede extraerse fácilmente de la lista *modelPP* (ver función `View(modelPP)`)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodelPP$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  (Intercept)                          edad \n                 0.7645004705                 -0.0003850228 \n                 hombreHombre estudios_universitarioscon EU \n                -0.0455226223                  0.1203369895 \n               ecoperpositiva                ecoesppositiva \n                 0.1739256464                 -0.7292760576 \n                 recuerdo19PP                 recuerdo19VOX \n                 4.1491958693                  0.5807105360 \n            recuerdo19Podemos          recuerdo19Ciudadanos \n                -0.9699832612                  2.8373014511 \n         recuerdo19Más Madrid               recuerdo19Otros \n                -0.5541319048                 -1.0125132971 \n          recuerdo19En blanco                         ideol \n                 0.6665536962                  0.4455040602 \n```\n\n\n:::\n:::\n\n\n\nVamos a ver algunos ejemplos:\n\n-   El *coeficiente de estudios_universitarioscon_ES* (0.1203) indica que, manteniendo constantes todas las demás variables, tener estudios universitarios está asociado con un aumento de 0.1203 unidades en la propensión de voto al Partido Popular. En otras palabras, las personas con estudios universitarios tienen, en promedio, una mayor inclinación a votar por el Partido Popular en comparación con aquellas que no tienen estudios universitario (*ceteris paribus*)\n-   El *coeficiente de recuerdo19PP* (4.149) indica que, manteniendo constantes todas las demás variables, las personas que recuerdan haber votado al Partido Popular en las elecciones de 2019 tienen una propensión de voto al Partido Popular 4.149 unidades mayor en comparación con aquellas que recuerdan haber votado al PSOE (la categoría de referencia). Esto significa que, en términos de propensión al voto, el recuerdo de haber votado al PP en el pasado está fuertemente asociado con una mayor inclinación a votar nuevamente por este partido, mucho más que en comparación con aquellos que votaron al PSOE (*ceteris paribus*)\n\n#### Visualizacion de los coeficientes\n\nUna manera rápida de presentar los resultados de la regresión es representar gráficamente los coeficientes. Para ello, podemos usar la función `coefplot()`\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_load(arm)\ncoefplot(modelPP, xlim=c(-5, 5),col.pts=\"blue\", intercept=TRUE, main=\"Coeficientes de la regresión\")\n```\n\n::: {.cell-output-display}\n![](52_reg_multiple_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\nEste tipo de gráfico es particularmente útil cuando queremos **comparar los coeficientes de dos o más modelos**. Por ejemplo, si calculamos el mismo modelo para estimar la propensión de voto al PSOE, podemos visualizar los coeficientes de ambos modelos de la siguiente manera\n\n\n\n::: {.cell layout-align=\"center\" fig.heigh='3' fig.with='5'}\n\n```{.r .cell-code}\n#Estimamos el modelo\nmodelPSOE <- lm(prop_psoe ~ edad + hombre + estudios_universitarios + ecoper + ecoesp + recuerdo19 + ideol, data=datos_red)   \n\n#Representamos gráficamente los coeficientes de ambas regresiones (argumento add=T)\npar(mfrow = c(1,1))\ncoefplot(modelPP, xlim=c(-5, 5),col.pts=\"blue\", intercept=TRUE, main=\"Coeficientes\")\ncoefplot(modelPSOE, add=TRUE, col.pts=\"red\",  intercept=TRUE, offset=0.2, main=\"PSOE\") \n\n#Añadimos leyenda\nlegend(\"topright\",  \n       c(\"Propensión voto PP\", \"Propensión voto PSOE\"), \n       lty = c(1,1),       \n       col=c(\"blue\",\"red\"),\n       cex = 0.7)\n```\n\n::: {.cell-output-display}\n![](52_reg_multiple_files/figure-html/fig1-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n#### ¿Qué variable es la más importante?\n\nDado que las variables están expresadas en diferentes unidades, los coeficientes de la regresión no son directamente comparables entre sí. Para hacer esto posible, es necesario transformar dichos coeficientes en coeficientes estandarizados (coeficientes Beta). Los coeficientes estandarizados se basan en puntuaciones típicas y, por lo tanto, son comparables entre sí.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_load(lm.beta)\nbetaPP<-lm.beta(modelPP)\nsummary(betaPP)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = prop_pp ~ edad + hombre + estudios_universitarios + \n    ecoper + ecoesp + recuerdo19 + ideol, data = datos_red)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.6522 -1.4692 -0.2591  1.5518  9.8268 \n\nCoefficients:\n                               Estimate Standardized Std. Error t value\n(Intercept)                    0.764501           NA   0.082283   9.291\nedad                          -0.000385    -0.001541   0.001114  -0.346\nhombreHombre                  -0.045523    -0.005909   0.033180  -1.372\nestudios_universitarioscon EU  0.120337     0.015627   0.034416   3.497\necoperpositiva                 0.173926     0.020009   0.038775   4.485\necoesppositiva                -0.729276    -0.091072   0.038624 -18.881\nrecuerdo19PP                   4.149196     0.442365   0.055763  74.407\nrecuerdo19VOX                  0.580711     0.040263   0.075540   7.687\nrecuerdo19Podemos             -0.969983    -0.080576   0.056628 -17.129\nrecuerdo19Ciudadanos           2.837302     0.197182   0.068713  41.292\nrecuerdo19Más Madrid          -0.554132    -0.012506   0.189993  -2.917\nrecuerdo19Otros               -1.012513    -0.089720   0.052845 -19.160\nrecuerdo19En blanco            0.666554     0.020676   0.139864   4.766\nideol                          0.445504     0.310399   0.008478  52.549\n                              Pr(>|t|)    \n(Intercept)                    < 2e-16 ***\nedad                          0.729637    \nhombreHombre                  0.170080    \nestudios_universitarioscon EU 0.000472 ***\necoperpositiva                7.31e-06 ***\necoesppositiva                 < 2e-16 ***\nrecuerdo19PP                   < 2e-16 ***\nrecuerdo19VOX                 1.56e-14 ***\nrecuerdo19Podemos              < 2e-16 ***\nrecuerdo19Ciudadanos           < 2e-16 ***\nrecuerdo19Más Madrid          0.003542 ** \nrecuerdo19Otros                < 2e-16 ***\nrecuerdo19En blanco           1.89e-06 ***\nideol                          < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.473 on 22880 degrees of freedom\nMultiple R-squared:  0.5873,\tAdjusted R-squared:  0.5871 \nF-statistic:  2505 on 13 and 22880 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nLos coeficientes estandarizados representan la cantidad de cambio, en unidades de desviación estándar, que se producirá en la variable dependiente por cada aumento de una unidad de desviación estándar en la correspondiente variable independiente (manteniendo constantes las demás variables). Al estandarizar las variables, la constante se iguala a 0, por lo que no se incluye en la ecuación de predicción. Estos coeficientes indican la importancia relativa de cada variable independiente en la ecuación de regresión. En general, cuanto mayor es el valor absoluto del coeficiente de regresión estandarizado, mayor es el peso de la variable en la ecuación de regresión.\n\n#### Bondad de ajuste del modelo\n\nEl R^2^ tiene un valor de 0.5873, lo que indica que nuestro modelo explica el 58.73% de varianza de la VD. En este caso, el valor de R^2^ ajustado es prácticamente idéntico.\n\n### Diagnóstico de la regresión {#supuestoS}\n\nVamos a comprobar los supuestos de la regresión\n\n1.  *Normalidad de los residuos*. El test de normalidad que usamos en el ejemplo de regresión simple (*Shapiro test*) está limitado a n=5000. Dado que no tenemos esa opción, vamos a revisar el supuesto de normalidad un gráfico Q-Q:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(modelPP, 2)\n```\n\n::: {.cell-output-display}\n![](52_reg_multiple_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\nComprobamos también que la media de los residuos=0\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(modelPP$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2.04219e-16\n```\n\n\n:::\n:::\n\n\n\n2.  *Homocedasticidad* (varianza constante de los residuos)\n\n-   Test de homocedasticidad\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#install.packages(\"lmtest\")\nlibrary(lmtest)\nhet.lm<-bptest(modelPP)\nhet.lm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modelPP\nBP = 2557.5, df = 13, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nLa hipótesis nula en este test es que la varianza de los residuos es constante (homocedástica). La evidencia permite rechazar la hipótesis nula, confirmando que la distribución es heterocedástica (no se cumple el suspuesto). La distrivución de los residuos no es constante.\n\n-   Gráficamente:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot( modelPP, 3)\n```\n\n::: {.cell-output-display}\n![](52_reg_multiple_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n3.  *Multicolinealidad*.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nreg.lineal.vif <- car::vif(modelPP)\nreg.lineal.vif\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            GVIF Df GVIF^(1/(2*Df))\nedad                    1.102517  1        1.050008\nhombre                  1.028258  1        1.014030\nestudios_universitarios 1.107391  1        1.052327\necoper                  1.103228  1        1.050347\necoesp                  1.289873  1        1.135726\nrecuerdo19              2.198730  7        1.057891\nideol                   1.934408  1        1.390830\n```\n\n\n:::\n:::\n\n\n\nNo parece que existan problemas de multicolinealidad en nuestro modelo. <br>\n\n### Valores predichos {#predichos}\n\nAl igual que hicimos con los coeficientes, una vez calculado el modelo podemos extraer los valores predichos (estimados) para cada individuo en la muestra consultando `modelPP$fitted.values`. Esto nos permite, por ejemplo, calcular el valor medio de propensión de voto al PP:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(modelPP$fitted.values)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.678606\n```\n\n\n:::\n:::\n\n\n\nTambién podemos estimar qué valor tendrá la variable dependiente para determinados valores de las variables independientes. Por ejemplo, vamos a calcular la propensión de voto al PP de un varón de 50 años, sin estudios universitarios (0), que valora positivamente su situación económica personal (1) pero no la situación económica del país (0), con ideología 5 y que en las elecciones de 2019 votó a C\\`s.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata1 <- data.frame(hombre=\"Hombre\", edad=50, estudios_universitarios=\"con EU\", ecoper=\"positiva\", ecoesp=\"negativa\", ideol=5, recuerdo19=\"Ciudadanos\")\nyhat1<-predict(modelPP, newdata = data1)\nyhat1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n6.058811 \n```\n\n\n:::\n:::\n\n\n\nO calcular, por ejemplo, cómo cambia la propensión de voto al PP para un individuo con esas mismas características en función de su edad:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata2<- data.frame(hombre=\"Hombre\", edad=c(20, 30, 40, 50, 60, 70, 80), estudios_universitarios=\"con EU\", ecoper=\"positiva\", ecoesp=\"negativa\", ideol=5, recuerdo19=\"Ciudadanos\")\nyhat2<-predict(modelPP, newdata = data2)\nyhat2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1        2        3        4        5        6        7 \n6.070362 6.066512 6.062661 6.058811 6.054961 6.051111 6.047260 \n```\n\n\n:::\n:::\n\n\n\n#### Intervalos de confianza\n\nLos intervalos de confianza reflejan la incertidumbre alrededor de las estimaciones medias. Siguiendo con el ejemplo anterior, vamos a calcular las probabilidades predichas con sus intervalos de confianza para todos los individuos en la muestra (*fit es el valor predicho*):\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nyhat<-predict(modelPP, newdata = datos_red, interval = \"confidence\")\nhead(yhat) #visualizamos los 5 primeros casos\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        fit       lwr       upr\n1 7.0760579 6.9727774 7.1793383\n2 8.1922896 8.0917476 8.2928316\n3 8.0114335 7.9169740 8.1058930\n4 0.5837394 0.4690074 0.6984715\n5 3.6770243 3.5669840 3.7870646\n6 1.9297500 1.8417350 2.0177651\n```\n\n\n:::\n:::\n\n\n\nSi no queremos ver los casos perdidos usamos el argumento *na.action* para especificarlo\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nyhat<-predict(modelPP, newdata = datos_red, interval = \"confidence\", na.action=na.exclude)\nhead(yhat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        fit       lwr       upr\n1 7.0760579 6.9727774 7.1793383\n2 8.1922896 8.0917476 8.2928316\n3 8.0114335 7.9169740 8.1058930\n4 0.5837394 0.4690074 0.6984715\n5 3.6770243 3.5669840 3.7870646\n6 1.9297500 1.8417350 2.0177651\n```\n\n\n:::\n:::\n\n\n\nEl *output* contiene 3 columnas:\n\n-   FIT: el valor predicho (que también habíamos consultado a través de `modelPP$fitted.values`)\n-   LWR: límite inferior de la banda de confianza\n-   UPR: límite superior de la banda de confianza\n\nPor defecto, R produce bandas de confianza al 95%, pero esto se puede cambiar con el argumento *level*\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nyhat<-predict(modelPP, newdata = datos_red, interval = \"confidence\", na.action=na.exclude, level=0.99)\nhead(yhat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        fit       lwr       upr\n1 7.0760579 6.9403202 7.2117955\n2 8.1922896 8.0601510 8.3244282\n3 8.0114335 7.8872889 8.1355781\n4 0.5837394 0.4329514 0.7345275\n5 3.6770243 3.5324024 3.8216462\n6 1.9297500 1.8140751 2.0454250\n```\n\n\n:::\n:::\n\n\n\n### Exportar resultados {#Exportar}\n\nVamos a exportar a formato científico los dos modelos que hemos estimado: modelPP y modelPSOE\n\n#### Librería stargazer\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#install.packages(\"stargazer\")\nlibrary(stargazer)\nstargazer(modelPP, modelPSOE,      #Incluir aquí Modelo1, Modelo2, M3...\n          type=\"text\",\n          dep.var.labels=c(\"Propensión voto PP\", \"Propensión voto PSOE\"),\n          covariate.labels=c(\"Edad\", \"Hombre\", \"Estudios superiores\", \"Economia personal: positiva (cr:neg)\", \"Economia país: positiva (cr:neg)\", \"Voto 2019:PP (cr: PSOE)\", \"Voto 2019:VOX (cr: PSOE)\", \"Voto 2019:Podemos (cr: PSOE)\", \"Voto 2019:C´s (cr: PSOE)\", \"Voto 2019:Más Madrid (cr: PSOE)\", \"Voto 2019:Otros (cr: PSOE)\", \"Voto 2019:Blanco (cr: PSOE)\", \"Ideología\", \"Constante\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n============================================================================\n                                               Dependent variable:          \n                                     ---------------------------------------\n                                     Propensión voto PP Propensión voto PSOE\n                                            (1)                 (2)         \n----------------------------------------------------------------------------\nEdad                                      -0.0004             0.011***      \n                                          (0.001)             (0.001)       \n                                                                            \nHombre                                     -0.046            -0.536***      \n                                          (0.033)             (0.034)       \n                                                                            \nEstudios superiores                       0.120***           -0.220***      \n                                          (0.034)             (0.035)       \n                                                                            \nEconomia personal: positiva (cr:neg)      0.174***             0.073*       \n                                          (0.039)             (0.040)       \n                                                                            \nEconomia país: positiva (cr:neg)         -0.729***            1.597***      \n                                          (0.039)             (0.040)       \n                                                                            \nVoto 2019:PP (cr: PSOE)                   4.149***           -4.966***      \n                                          (0.056)             (0.057)       \n                                                                            \nVoto 2019:VOX (cr: PSOE)                  0.581***           -5.070***      \n                                          (0.076)             (0.077)       \n                                                                            \nVoto 2019:Podemos (cr: PSOE)             -0.970***           -2.444***      \n                                          (0.057)             (0.058)       \n                                                                            \nVoto 2019:C´s (cr: PSOE)                  2.837***           -4.226***      \n                                          (0.069)             (0.070)       \n                                                                            \nVoto 2019:Más Madrid (cr: PSOE)          -0.554***           -1.982***      \n                                          (0.190)             (0.195)       \n                                                                            \nVoto 2019:Otros (cr: PSOE)               -1.013***           -3.589***      \n                                          (0.053)             (0.054)       \n                                                                            \nVoto 2019:Blanco (cr: PSOE)               0.667***           -3.927***      \n                                          (0.140)             (0.143)       \n                                                                            \nIdeología                                 0.446***           -0.305***      \n                                          (0.008)             (0.009)       \n                                                                            \nConstante                                 0.765***            7.650***      \n                                          (0.082)             (0.084)       \n                                                                            \n----------------------------------------------------------------------------\nObservations                               22,894              22,894       \nR2                                         0.587               0.593        \nAdjusted R2                                0.587               0.592        \nResidual Std. Error (df = 22880)           2.473               2.532        \nF Statistic (df = 13; 22880)            2,504.777***        2,560.708***    \n============================================================================\nNote:                                            *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\n\n#### Librería jtools\n\nEstá disponible únicamente para un tipo de modelos muy limitado, pero OLS y GLM están incluidos.\n\nInstalamos los paquetes que van a hacernos falta\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_load(jtools, ggstance, huxtable)\n```\n:::\n\n\n\nLa función `summ()` muestra los resultados de la regresión\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsumm(modelPP)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMODEL INFO:\nObservations: 22894\nDependent Variable: prop_pp\nType: OLS linear regression \n\nMODEL FIT:\nF(13,22880) = 2504.78, p = 0.00\nR² = 0.59\nAdj. R² = 0.59 \n\nStandard errors:OLS\n-------------------------------------------------------------\n                                  Est.   S.E.   t val.      p\n------------------------------ ------- ------ -------- ------\n(Intercept)                       0.76   0.08     9.29   0.00\nedad                             -0.00   0.00    -0.35   0.73\nhombreHombre                     -0.05   0.03    -1.37   0.17\nestudios_universitarioscon        0.12   0.03     3.50   0.00\nEU                                                           \necoperpositiva                    0.17   0.04     4.49   0.00\necoesppositiva                   -0.73   0.04   -18.88   0.00\nrecuerdo19PP                      4.15   0.06    74.41   0.00\nrecuerdo19VOX                     0.58   0.08     7.69   0.00\nrecuerdo19Podemos                -0.97   0.06   -17.13   0.00\nrecuerdo19Ciudadanos              2.84   0.07    41.29   0.00\nrecuerdo19Más Madrid             -0.55   0.19    -2.92   0.00\nrecuerdo19Otros                  -1.01   0.05   -19.16   0.00\nrecuerdo19En blanco               0.67   0.14     4.77   0.00\nideol                             0.45   0.01    52.55   0.00\n-------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n\nLa representación gráfica de los coeficientes también se hace de manera muy sencilla y muy parecida a la que ya conocemos\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_summs(modelPP)\n```\n\n::: {.cell-output-display}\n![](52_reg_multiple_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\nSe pueden añadir tantos modelos como deseemos\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_summs(modelPP, modelPSOE)\n```\n\n::: {.cell-output-display}\n![](52_reg_multiple_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\nTambién permite visualizar de manera rápida el efecto de una variable sobre la variable dependiente, siempre que la primera sea continua. Por ejemplo, vamos cómo varía la propensión de votar al PP con la ideología, controlado por el resto de variables\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neffect_plot(modelPP, pred = ideol, interval = TRUE)\n```\n\n::: {.cell-output-display}\n![](52_reg_multiple_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\nFinalmente, la función export_summs de jtools permite representar las tablas en formato \"científico\".\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexport_summs(modelPP, modelPSOE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"huxtable\" data-quarto-disable-processing=\"true\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \">\n<col><col><col><tr>\n<th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 1</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Model 2</th></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(Intercept)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.76 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">7.65 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.08)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.08)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">edad</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.00&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.01 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">hombreHombre</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.05&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.54 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.03)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.03)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">estudios_universitarioscon EU</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.12 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.22 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.03)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">ecoperpositiva</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.17 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.07&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">ecoesppositiva</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.73 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">1.60 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">recuerdo19PP</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">4.15 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-4.97 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.06)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.06)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">recuerdo19VOX</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.58 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-5.07 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.08)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.08)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">recuerdo19Podemos</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.97 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-2.44 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.06)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.06)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">recuerdo19Ciudadanos</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">2.84 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-4.23 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.07)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.07)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">recuerdo19Más Madrid</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.55 **&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-1.98 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.19)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.19)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">recuerdo19Otros</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-1.01 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-3.59 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.05)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.05)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">recuerdo19En blanco</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.67 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-3.93 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.14)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.14)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">ideol</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.45 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.31 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.01)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.01)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">N</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">22894&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">22894&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">R2</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.59&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.59&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th colspan=\"3\" style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>\n</table>\n\n```\n\n:::\n:::\n\n\n\nPara renombrar los modelos y las variables, usaremos los argumentos model.names y coefs de la siguiente manera\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexport_summs(modelPP, modelPSOE, \n  model.names=c(\"Prop. Voto PP\", \n                \"Prop. Voto PSOE\"), \n  coefs=c(\"Edad\"=\"edad\", \n          \"Hombre\"=\"hombreHombre\", \n          \"Estudios Universitarios\"=\"estudios_universitarioscon EU\", \n          \"Economía personal positiva (cr=neg)\"=\"ecoperpositiva\", \n          \"Economía país positiva (cr=neg)\"=\"ecoesppositiva\", \n          \"Voto 2019:PP (cr=PSOE)\"=\"recuerdo19PP\",\n          \"Voto 2019:VOX (cr=PSOE)\"=\"recuerdo19VOX\",\n          \"Voto 2019:Podemos (cr=PSOE)\"=\"recuerdo19Podemos\",\n          \"Voto 2019:C´s (cr=PSOE)\"=\"recuerdo19Ciudadanos\",\n          \"Voto 2019:Mas País (cr=PSOE)\"=\"recuerdo19Más Madrid\",\n          \"Voto 2019:Otros (cr=PSOE)\"=\"recuerdo19Otros\",\n          \"Voto 2019:Blanco (cr=PSOE)\"=\"recuerdo19En blanco\",\n          \"Ideología\"=\"ideol\",\n          \"Constante\"=\"(Intercept)\"\n))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"huxtable\" data-quarto-disable-processing=\"true\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \">\n<col><col><col><tr>\n<th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Prop. Voto PP</th><th style=\"vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Prop. Voto PSOE</th></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Edad</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.00&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.01 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.00)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Hombre</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.05&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.54 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.03)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.03)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Estudios Universitarios</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.12 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.22 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.03)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Economía personal positiva (cr=neg)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.17 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.07&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Economía país positiva (cr=neg)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.73 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">1.60 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.04)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Voto 2019:PP (cr=PSOE)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">4.15 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-4.97 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.06)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.06)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Voto 2019:VOX (cr=PSOE)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.58 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-5.07 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.08)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.08)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Voto 2019:Podemos (cr=PSOE)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.97 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-2.44 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.06)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.06)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Voto 2019:C´s (cr=PSOE)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">2.84 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-4.23 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.07)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.07)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Voto 2019:Mas País (cr=PSOE)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.55 **&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-1.98 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.19)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.19)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Voto 2019:Otros (cr=PSOE)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-1.01 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-3.59 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.05)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.05)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Voto 2019:Blanco (cr=PSOE)</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.67 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-3.93 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.14)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.14)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Ideología</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.45 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">-0.31 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.01)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.01)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">Constante</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.76 ***</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">7.65 ***</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"></th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.08)&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">(0.08)&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">N</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">22894&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">22894&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">R2</th><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.59&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">0.59&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>\n<tr>\n<th colspan=\"3\" style=\"vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>\n</table>\n\n```\n\n:::\n:::\n\n\n\n### Comparación de modelos {#comparar_modelos}\n\nEs muy frecuente tener que elegir entre diferentes modelos. Hasta ahora, nos hemos fijado en el R^2^ para ver cuál era la bondad de ajuste del modelo. Aquí, vamos a introducir dos nuevos indicadores: **BIC** (Criterio de Información Bayesiano) y **AIC** (Criterio de Información de Akaike).\n\nCuando introducimos nuevas variables en el modelo aumentamos el ajuste (a mayor número de variables, mayor R^2^), pero corremos el peligro de caer en sobreajuste (introducir demasiadas variables, siendo algunas de ellas innecesarias para el modelo). Solo es conveniente incluir más variables en un modelo si la diferencia que añaden sobre la significatividad del modelo es lo suficiente relevante. BIC y AIC resuelven este problema mediante la introducción de un término de penalización para el número de parámetros en el modelo (esta penalización es mayor en el BIC que en el AIC). Así, dados dos modelos estimados, el modelo con el menor valor de BIC/AIC es preferible. Existe también el AIC corregido (AICc), que es una variante del AIC para muestras reducidas (pocos datos).\n\n*No es necesario realizar los dos análisis, sino que con uno de los dos es suficiente para ver qué modelo es más eficiente.*\n\nEstimamos los modelos con el dataset reducido. El modelo1 incluye sólamente la variable ideología. El modelo2 añade el sexo y el nivel educativo. El modelo3 es el full-model, que incluye la edad y la situación laboral del entrevistado.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodelo1 <- lm(prop_pp ~ hombre+estudios_universitarios, datos_red) \nmodelo2 <- lm(prop_pp ~ hombre+estudios_universitarios+ ideol, datos_red)  \nmodelo3 <- lm(prop_pp ~ hombre+estudios_universitarios+ideol+recuerdo19, datos_red)  \n```\n:::\n\n\n\nVisualizamos los 3 modelos en una misma tabla\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(stargazer)\nstargazer(modelo1, modelo2, modelo3,    \n          type=\"text\",\n          dep.var.labels=c(\"M1\", \"M2\", \"M3\"),\n          covariate.labels=c(\"Hombre\", \"Estudios superiores\",\"Ideología\", \"Voto 2019:PP (cr: PSOE)\", \"Voto 2019:VOX (cr: PSOE)\", \"Voto 2019:Podemos (cr: PSOE)\", \"Voto 2019:C´s (cr: PSOE)\", \"Voto 2019:Más Madrid (cr: PSOE)\", \"Voto 2019:Otros (cr: PSOE)\", \"Voto 2019:Blanco (cr: PSOE)\",  \"Constante\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=================================================================================================================\n                                                               Dependent variable:                               \n                                ---------------------------------------------------------------------------------\n                                                                       M1                                        \n                                         (1)                       (2)                           (3)             \n-----------------------------------------------------------------------------------------------------------------\nHombre                                 -0.112**                 -0.199***                     -0.110***          \n                                       (0.051)                   (0.039)                       (0.033)           \n                                                                                                                 \nEstudios superiores                     -0.007                   0.204***                     0.131***           \n                                       (0.051)                   (0.039)                       (0.033)           \n                                                                                                                 \nIdeología                                                        0.910***                     0.463***           \n                                                                 (0.007)                       (0.008)           \n                                                                                                                 \nVoto 2019:PP (cr: PSOE)                                                                       4.376***           \n                                                                                               (0.055)           \n                                                                                                                 \nVoto 2019:VOX (cr: PSOE)                                                                      0.842***           \n                                                                                               (0.074)           \n                                                                                                                 \nVoto 2019:Podemos (cr: PSOE)                                                                  -0.970***          \n                                                                                               (0.057)           \n                                                                                                                 \nVoto 2019:C´s (cr: PSOE)                                                                      3.069***           \n                                                                                               (0.068)           \n                                                                                                                 \nVoto 2019:Más Madrid (cr: PSOE)                                                               -0.535***          \n                                                                                               (0.191)           \n                                                                                                                 \nVoto 2019:Otros (cr: PSOE)                                                                    -0.914***          \n                                                                                               (0.053)           \n                                                                                                                 \nVoto 2019:Blanco (cr: PSOE)                                                                   0.901***           \n                                                                                               (0.140)           \n                                                                                                                 \nConstante                              3.741***                 -0.656***                     0.448***           \n                                       (0.045)                   (0.050)                       (0.047)           \n                                                                                                                 \n-----------------------------------------------------------------------------------------------------------------\nObservations                            22,894                    22,894                       22,894            \nR2                                      0.0002                    0.401                         0.581            \nAdjusted R2                             0.0001                    0.401                         0.581            \nResidual Std. Error               3.848 (df = 22891)        2.978 (df = 22890)           2.492 (df = 22883)      \nF Statistic                     2.434* (df = 2; 22891) 5,108.655*** (df = 3; 22890) 3,170.031*** (df = 10; 22883)\n=================================================================================================================\nNote:                                                                                 *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\n\nY calculamos los BIC/AIC\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAIC(modelo1, modelo2, modelo3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"huxtable\" data-quarto-disable-processing=\"true\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \">\n<col><col><tr>\n<th style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;\">df</th><th style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;\">AIC</th></tr>\n<tr>\n<td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;\">4</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;\">1.27e+05</td></tr>\n<tr>\n<td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">5</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">1.15e+05</td></tr>\n<tr>\n<td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;\">12</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;\">1.07e+05</td></tr>\n</table>\n\n```\n\n:::\n\n```{.r .cell-code}\nBIC(modelo1, modelo2, modelo3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<table class=\"huxtable\" data-quarto-disable-processing=\"true\" style=\"border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  \">\n<col><col><tr>\n<th style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;\">df</th><th style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;\">BIC</th></tr>\n<tr>\n<td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;\">4</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;\">1.27e+05</td></tr>\n<tr>\n<td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">5</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;\">1.15e+05</td></tr>\n<tr>\n<td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;\">12</td><td style=\"vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;\">1.07e+05</td></tr>\n</table>\n\n```\n\n:::\n:::\n\n\n\nDiferencias más notables:\n\n-   R^2^ ajustado es una medida de la varianza explicada en la variable de respuesta por los predictores, mientras que BIC/AIC son una compensación entre la bondad del ajuste y la complejidad del modelo.\n-   R^2^ puede subir o bajar según se agregue o no otra variable al modelo. Pero el AIC/BIC no necesariamente cambian con la adición de una variable, sino que cambia con la composición de los predictores.\n-   Otra ventaja adicional es que AIC/BIC permiten comparar entre modelos que no están anidados.\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "52_reg_multiple_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}