{
  "hash": "5b9f77a4f3a8bcf4481d5a4356886897",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"T-test\"\n---\n\n\n\n\n\n\n## Test de una media:\n\nEl objetivo de este tipo de test es comprobar si la media poblacional de una variable se corresponde con una determinada cifra.\n\n``` r\nt.test(datos$variable, mu = 5, conf.level = 0.99)\n```\n\n-   `mu = número` es donde se indica el valor de la media para el cual se quiere comprobar si la media poblacional es significativamente distinta. Es decir, si se quiere comprobar si la media es igual a 5, se escribirá `mu = 5`.\n-   `conf.level` sirve para establecer un intervalo de confianza específico. Si no se añade esta opción, el intervalo será al 95%.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(datos$ideol, mu=5.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  datos$ideol\nt = -43.622, df = 28265, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 5.5\n95 percent confidence interval:\n 4.785116 4.846597\nsample estimates:\nmean of x \n 4.815857 \n```\n\n\n:::\n:::\n\n\n\n\nEn este caso, se puede decir que al 95% de confianza la media ideológica de la población es distinta de 5.5 (en una escala del 1 al 10). Se sabe por tres motivos:\n\n-   El p-value es \\< de 0,05\n-   El valor de t \\< -1,96\n-   En el intervalo de confianza no se incluye el 5.5\n\n*La explicación del por qué está en el apartado de la teoría*\n\n## Test de proporciones\n\n**Para variables dicotómicas**. Lo que se intenta con este tipo de test no es comprobar si una determinada cifra se incluye dentro de la media poblacional, sino si una variable alcanza un determinado porcentaje.\n\nP.ej., para saber si el PP puede alcanzar un 35% de los votos, se crea una variable dicotómica donde 0 es no votarlo y 1 sí. Después, se hace un ttest como el anterior, pero en el mu se especifica el porcentaje que se quiere comprobar si se alcanza (0.35 en este caso).\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(datos$intvoto_pp, mu=0.35)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  datos$intvoto_pp\nt = -8.4891, df = 23428, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0.35\n95 percent confidence interval:\n 0.3180496 0.3300361\nsample estimates:\nmean of x \n0.3240429 \n```\n\n\n:::\n:::\n\n\n\n\nLos resultados se interpretan igual que en el test de una media.\n\n## Test de dos medias\n\nLa hipótesis nula en este tipo de prueba es que las dos medias son iguales y la hipótesis alternativa es que no lo son.\n\n``` r\nt.test(datos$var1 ~ datos$var2)\n```\n\n-   `var2` es la variable dicotómica que divide a la muestra en los dos grupos de interés, para los cuales se tratará de averiguar si la media de la\n-   `var1` (variable numérica) es igual en ambos o no.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(datos$ideol ~ datos$hombre)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  datos$ideol by datos$hombre\nt = -3.7778, df = 27496, p-value = 0.0001586\nalternative hypothesis: true difference in means between group Mujer and group Hombre is not equal to 0\n95 percent confidence interval:\n -0.1806671 -0.0572345\nsample estimates:\n mean in group Mujer mean in group Hombre \n            4.754256             4.873207 \n```\n\n\n:::\n:::\n\n\n\n\nLos resultados indican que la media de ideología de las mujeres en la muestra es 4.75 y la de los hombres 4.87. Esta diferencia es suficiente para rechazar la Ho, es decir, existen diferencias significativas en la ideología en función del género.\n\n## Comparación de medias para dos variables numéricas\n\nSi son **muestras independientes**:\n\n``` r\nt.test(datos$variable1, datos$variable2)\n```\n\nEn el caso de **muestras dependientes**, el comando es el siguiente:\n\n``` r\nt.test(datos$variable1, datos$variable2, paired = TRUE)\n```\n\nLa prueba t pareada se utiliza cuando las medias que estamos comparando no son independientes. En otras palabras:\n\n-   Correnponden al mismo conjunto de sujetos en dos momentos diferentes (por ejemplo, antes y después de un tratamiento).\n-   Se comparan dos variables medidas en las mismas personas o unidades (las mismas personas opinan o responden sobre dos cosas diferentes).\n\nEj.: comprobar si las personas tienen la misma probabilidad de votar al PP y VOX:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(datos$prop_vox, datos$prop_pp, paired=TRUE) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  datos$prop_vox and datos$prop_pp\nt = -69.828, df = 28775, p-value < 2.2e-16\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -1.652107 -1.561891\nsample estimates:\nmean difference \n      -1.606999 \n```\n\n\n:::\n:::\n\n\n\n\n------------------------------------------------------------------------\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}